autoSwitchLanguage = false
updateUrl = "https://vmct-cn.top/vault/update.txt"
downloadUrl = "https://vmct-cn.top/modpacks/vault/"
tipsUrl = "https://vmct-cn.top/tips.txt"
translationVersion = "2.4.4"
minutes = 25
packName = "VM汉化组模组汉化包1.18"
packUrl = "https://cdn.modrinth.com/data/IDWIdXwS/versions/xCpjJgHS/VM%E6%B1%89%E5%8C%96%E7%BB%84%E6%A8%A1%E7%BB%84%E6%B1%89%E5%8C%96%E5%8C%851.18"
